version: 2.1
parameters:
  connector-version:
    type: string
    default: "1.0.0"

orbs:
  win: circleci/windows@2.4.0

commands:
  setup-environment-ubuntu:
    description: Setup Linux environment
    steps:
      - run:
          name: Install .NET Core 6.0
          command: |
            wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y mariadb-client-core-10.3
            sudo apt-get install -y dotnet-sdk-6.0
            dotnet --info
  run-tests-win:
    description: Run tests on Windows
    parameters:
      target_framework:
        type: string
    steps:
      - run:
          name: Unit tests
          command: |
            cd tests\MySqlConnector.Tests
            dotnet.exe test -f << parameters.target_framework >> -c Release --no-build
            cd ..\..
      - run:
          name: Conformance tests
          command: |
            cd tests/Conformance.Tests/
            dotnet.exe test -f << parameters.target_framework >> -c Release --no-build
            cd ..\..
      - run:
          name: SideBySide tests
          command: |
            cd tests\SideBySide
            dotnet.exe test -f << parameters.target_framework >> -c Release --no-build
            cd ..\..

jobs:
  test-windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build project binaries
          command: |
            choco upgrade dotnet-sdk
            dotnet.exe build -c Release
      - run:
          name: Start SingleStore for SideBySide tests
          command: |
            pip install pymysql
            python.exe .circleci\s2ms_cluster.py start singlestoretest
      - run:
          name: Fill test config
          command: python.exe .circleci\fill_test_config.py
      - run-tests-win:
          target_framework: net6.0

  test-ubuntu:
    parameters:
      singlestore_image:
        type: string
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    environment:
      SINGLESTORE_IMAGE: << parameters.singlestore_image >>
    steps:
      - checkout
      - setup-environment-ubuntu
      - run:
          name: Start SingleStore for SideBySide tests
          command: |
            ./.circleci/setup_cluster.sh
      - run:
          name: Build connector
          command: |
            dotnet build -c Release
      - run:
          name: Copy config file for SideBySide tests
          command: |
            cp ./.circleci/SideBySide/config.json tests/SideBySide/config.json
            sed -i "s|SINGLESTORE_HOST|127.0.0.1|g" tests/SideBySide/config.json
            sed -i "s|SQL_USER_PASSWORD|${SQL_USER_PASSWORD}|g" tests/SideBySide/config.json
            sed -i "s|SQL_USER_NAME|root|g" tests/SideBySide/config.json
            cp tests/SideBySide/config.json tests/SideBySide/bin/Release/net6.0/config.json
      - run:
          name: Unit tests
          command: |
            cd tests/MySqlConnector.Tests
            dotnet test -f net6.0 -c Release --no-build
            cd ../../
      - run:
          name: Conformance tests
          command: |
            cd tests/Conformance.Tests/
            dotnet test -f net6.0 -c Release --no-build
            cd ../../
      - run:
          name: SideBySide tests
          command: |
            cd tests/SideBySide
            dotnet test -f net6.0 -c Release --no-build
            cd ../../

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-ubuntu:
          name: Test 7.6 cluster-in-a-box
          matrix:
            parameters:
              singlestore_image:
                - singlestore/cluster-in-a-box:centos-7.6.9-7d7e13942a-4.0.3-1.13.4
      - test-ubuntu:
          name: Test 7.5 cluster-in-a-box
          matrix:
            parameters:
              singlestore_image:
                - singlestore/cluster-in-a-box:centos-7.5.12-3112a491c2-4.0.0-1.12.5
      - test-ubuntu:
          name: Test 7.3 cluster-in-a-box
          matrix:
            parameters:
              singlestore_image:
                - singlestore/cluster-in-a-box:centos-7.3.13-761e3259b3-3.2.11-1.11.9
      - test-windows:
          name: Test S2MS on Windows
